# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sensors.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from .MPL_Plot import MplPlot
from matplotlib.backends.backend_qt5 import NavigationToolbar2QT as NavigationToolbar
import numpy as np

class Ui_Sensors(QWidget):
    def __init__(self):
        QWidget.__init__(self)
        self.setupUi(self)
        phase_fig_normal = MplPlot(width=6, height=3, dpi=72)
        fig_ntb_normal = NavigationToolbar(phase_fig_normal, self)
        gridlayout_normal = QGridLayout(self.NormalSensor)
        gridlayout_normal.addWidget(phase_fig_normal)
        gridlayout_normal.addWidget(fig_ntb_normal)

        phase_fig_lateral = MplPlot(width=6, height=3, dpi=72)
        fig_ntb_lateral = NavigationToolbar(phase_fig_lateral, self)
        gridlayout_lateral = QGridLayout(self.LateralSensor)
        gridlayout_lateral.addWidget(phase_fig_lateral)
        gridlayout_lateral.addWidget(fig_ntb_lateral)

        xdata_normal, xdata_lateral = np.arange(-10, 0, 0.05), np.arange(-10, 0, 0.05)
        ydata_normal, ydata_lateral = np.zeros(xdata_normal.shape).tolist(), np.zeros(xdata_lateral.shape).tolist()
        xdata_normal, xdata_lateral = xdata_normal.tolist(), xdata_lateral.tolist()
        phase_fig_normal.add_line(xdata_normal, ydata_normal)
        phase_fig_lateral.add_line(xdata_lateral, ydata_lateral)

        self.xdata = {"sensor_normal": xdata_normal, "sensor_lateral": xdata_lateral}
        self.ydata = {"sensor_normal": ydata_normal, "sensor_lateral": ydata_lateral}
        self.phase_fig = {"sensor_normal": phase_fig_normal, "sensor_lateral": phase_fig_lateral}

    def clear(self):
        self.phase_fig["sensor_normal"].clear()
        self.phase_fig["sensor_lateral"].clear()

    def setupUi(self, Sensors):
        Sensors.setObjectName("Sensors")
        Sensors.resize(934, 765)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Sensors.sizePolicy().hasHeightForWidth())
        Sensors.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(Sensors)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.NormalSensor = QtWidgets.QGroupBox(Sensors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NormalSensor.sizePolicy().hasHeightForWidth())
        self.NormalSensor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.NormalSensor.setFont(font)
        self.NormalSensor.setObjectName("NormalSensor")
        self.gridLayout.addWidget(self.NormalSensor, 0, 0, 1, 1)
        self.LateralSensor = QtWidgets.QGroupBox(Sensors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LateralSensor.sizePolicy().hasHeightForWidth())
        self.LateralSensor.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.LateralSensor.setFont(font)
        self.LateralSensor.setObjectName("LateralSensor")
        self.gridLayout.addWidget(self.LateralSensor, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 4)
        self.Connect = QtWidgets.QPushButton(Sensors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Connect.sizePolicy().hasHeightForWidth())
        self.Connect.setSizePolicy(sizePolicy)
        self.Connect.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Connect.setFont(font)
        self.Connect.setObjectName("Connect")
        self.gridLayout_2.addWidget(self.Connect, 1, 0, 1, 1)
        self.Record = QtWidgets.QPushButton(Sensors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Record.sizePolicy().hasHeightForWidth())
        self.Record.setSizePolicy(sizePolicy)
        self.Record.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Record.setFont(font)
        self.Record.setObjectName("Record")
        self.gridLayout_2.addWidget(self.Record, 1, 1, 1, 1)
        self.Rezero = QtWidgets.QPushButton(Sensors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Rezero.sizePolicy().hasHeightForWidth())
        self.Rezero.setSizePolicy(sizePolicy)
        self.Rezero.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Rezero.setFont(font)
        self.Rezero.setObjectName("Rezero")
        self.gridLayout_2.addWidget(self.Rezero, 1, 2, 1, 1)
        self.Disconnect = QtWidgets.QPushButton(Sensors)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Disconnect.sizePolicy().hasHeightForWidth())
        self.Disconnect.setSizePolicy(sizePolicy)
        self.Disconnect.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Disconnect.setFont(font)
        self.Disconnect.setObjectName("Disconnect")
        self.gridLayout_2.addWidget(self.Disconnect, 1, 3, 1, 1)

        self.retranslateUi(Sensors)
        QtCore.QMetaObject.connectSlotsByName(Sensors)

    def retranslateUi(self, Sensors):
        _translate = QtCore.QCoreApplication.translate
        Sensors.setWindowTitle(_translate("Sensors", "Form"))
        self.NormalSensor.setTitle(_translate("Sensors", "Normal Sensor"))
        self.LateralSensor.setTitle(_translate("Sensors", "Lateral Sensor"))
        self.Connect.setText(_translate("Sensors", "Connect"))
        self.Record.setText(_translate("Sensors", "Record"))
        self.Rezero.setText(_translate("Sensors", "Rezero"))
        self.Disconnect.setText(_translate("Sensors", "Disconnect"))
